alertmanager:
  enabled: false
grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"    
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
    - grafana.fabijanbajo.com
    path: /
    tls:
    - secretName: grafana-tls-secret
      hosts:
      - grafana.fabijanbajo.com
