---
- hosts: all
  become: yes
  tasks:
  - name: create admin user k8s with sudo privileges
    user: name=k8s append=yes state=present createhome=yes shell=/bin/bash
  
  - name: allow user to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      line: "k8s ALL=(ALL) NOPASSWD: ALL"
      validate: visudo -cf %s
  
  - name: add ssh key to authorized_keys
    authorized_key: user=k8s key={{item}}
    with_file:
    - ~/.ssh/id_rsa.pub

- hosts: worker-0
  become: yes
  tasks:
  # Hezner floating IP needs to be configured on all worker nodes
  - copy:
      src: ./manifests/60-floating-ip.cfg
      dest: /etc/network/interfaces.d/60-floating-ip.cfg
  - name: restart network service
    systemd:
      name: networking.service
      state: restarted

- hosts: all
  become: yes
  tasks:
  # MUST disable swap in order for the kubelet to work properly        
  - name: remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
  - name: disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  # letting iptables see bridged traffic
  - copy:
      src: ./manifests/bridged-traffic.conf
      dest: /etc/sysctl.d/k8s.conf
  - name: reload sysctl conf
    command: sysctl --system
  
  - name: install packages for apt over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
